# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cbba36e3c20aa1c988dd6de22bba6b32f3b69f095a9831578c8fa57e6892c9b1ca90ce290dbd83787825de9a67d7dada90cadbfe1df3525c76e6849e8248859

test:
  secret_key_base: fbea9a35b23c5891b6a0d7c81bea89189f763d82e41954ce80dccc036a6455f7be49da22792b5987f51054ff6a18c91f2675377bfaf6e8139325270b6eda50c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
